In [1]:
import pandas as pd

In [2]:
# Read the DataFrame and save it in the variable df.
df = pd.read_excel('C:\Language_Projects\Language_Projects\Python\Flagship_1\Immo_Assistant.app\data\year_make_model_df.xlsx')

<>:2: SyntaxWarning: invalid escape sequence '\L'
<>:2: SyntaxWarning: invalid escape sequence '\L'
C:\Users\Weverson Barbieri\AppData\Local\Temp\ipykernel_16248\507487594.py:2: SyntaxWarning: invalid escape sequence '\L'
  df = pd.read_excel('C:\Language_Projects\Language_Projects\Python\Flagship_1\Immo_Assistant.app\data\year_make_model_df.xlsx')

In [3]:
# Converting all values in column Model to string, as some of models are numbers, for instance BMWs 318, 328, 525
df = df.astype({'Model':'string'})

In [4]:
# Confirm if the Dtype from the column Model changed to string.
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3463 entries, 0 to 3462
Data columns (total 5 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Year            3463 non-null   int64
 1   Make            3463 non-null   object
 2   Model           3463 non-null   string
 3   Security        3156 non-null   object
 4   ParameterReset  938 non-null    object
dtypes: int64(1), object(3), string(1)
memory usage: 135.4+ KB

In [5]:
# Check which models the df has and print only the unique values
models = df['Model'].unique()

In [6]:
# Filter only Ford models and create a df.
df_ford = df[df['Make'] == 'Ford']

In [11]:
# Iterate on column 'Security' to verify all
for security_info in df_ford['Security']:
    print(security_info)

PATS Type A (Stand Alone PATS Module)
PATS Type A (Stand Alone PATS Module)
PATS Type A (Stand Alone PATS Module)
PATS Type A (Stand Alone PATS Module)
PATS Type A (Stand Alone PATS Module)
Built February 1st or earlier: PATS Type A (Stand Alone PATS Module)
Built February 2nd or later: PATS Type E (Powertrain Control Module)
PATS Type B (Stand Alone PATS Module)
PATS Type A (Stand Alone PATS Module)
PATS Type B (Stand Alone PATS Module)
PATS Type B (Stand Alone PATS Module)
PATS Type B (Stand Alone PATS Module)
PATS Type B (Stand Alone PATS Module)
PATS Type E (Powertrain Control Module)
PATS Type B (Stand Alone PATS Module)
PATS Type C (Instrument Cluster)
PATS Type B (Stand Alone PATS Module)
PATS Type B (Stand Alone PATS Module)
PATS Type C (Instrument Cluster)
PATS Type C (Instrument Cluster)
PATS Type C (Instrument Cluster)
PATS Type B (Stand Alone PATS Module)
PATS Type B (Stand Alone PATS Module)
PATS Type C (Instrument Cluster)
PATS Type E (Powertrain Control Module)
PATS Type B (Stand Alone PATS Module)
PATS Type B (Stand Alone PATS Module)
PATS Type C (Instrument Cluster)
PATS Type B (Stand Alone PATS Module)
PATS Type B (Stand Alone PATS Module)
PATS Type C (Instrument Cluster)
PATS Type C (Instrument Cluster)
PATS Type E (Powertrain Control Module)
PATS Type C (Instrument Cluster)
PATS Type B (Stand Alone PATS Module)
PATS Type E (Powertrain Control Module)
PATS Type C (Instrument Cluster)
PATS Type B (Stand Alone PATS Module)
PATS Type E (Powertrain Control Module)
PATS Type B (Stand Alone PATS Module)
PATS Type C (Instrument Cluster)
PATS Type B (Stand Alone PATS Module)
Built July 23rd 2000 or Earlier: PATS Type B (Stand Alone PATS Module)
Built July 24th 2000 or Later: PATS Type E (Powertrain Control Module)
Built July 23rd 2000 or Earlier: PATS Type B (Stand Alone PATS Module)
Built July 24th 2000 or Later: PATS Type E (Powertrain Control Module)
PATS Type C (Instrument Cluster)
PATS Type C (Instrument Cluster)
PATS Type E (Powertrain Control Module)
PATS Type C (Instrument Cluster)
PATS Type E (Powertrain Control Module)
PATS Type E (Powertrain Control Module)
PATS Type E (Powertrain Control Module)
PATS Type B (Stand Alone PATS Module)
PATS Type E (Powertrain Control Module)
PATS Type B (Stand Alone PATS Module)
PATS Type C (Instrument Cluster)
PATS Type E (Powertrain Control Module)
PATS Type E (Powertrain Control Module)
PATS Type E (Powertrain Control Module)
PATS Type C (Instrument Cluster)
PATS Type C (Instrument Cluster)
PATS Type E (Powertrain Control Module)
PATS Type C (Instrument Cluster)
PATS Type E (Powertrain Control Module)
PATS Type E (Powertrain Control Module)
PATS Type C (Instrument Cluster)
PATS Type E (Powertrain Control Module)
PATS Type E (Powertrain Control Module)
PATS Type E (Powertrain Control Module)
PATS Type B (Stand Alone PATS Module)
PATS Type E (Powertrain Control Module)
PATS Type E (Powertrain Control Module)
PATS Type E (Powertrain Control Module)
PATS Type E (Powertrain Control Module)
PATS Type C (Instrument Cluster)
PATS Type C (Instrument Cluster)
PATS Type E (Powertrain Control Module)
PATS Type C (Instrument Cluster)
PATS Type E (Powertrain Control Module)
PATS Type E (Powertrain Control Module)
PATS Type C (Instrument Cluster)
PATS Type E (Powertrain Control Module)
PATS Type E (Powertrain Control Module)
PATS Type E (Powertrain Control Module)
PATS Type B (Stand Alone PATS Module)
PATS Type E (Powertrain Control Module)
PATS Type E (Powertrain Control Module)
PATS Type E (Powertrain Control Module)
PATS Type E (Powertrain Control Module)
PATS Type C (Instrument Cluster)
PATS Type E (Powertrain Control Module)
PATS Type E (Powertrain Control Module)
PATS Type C (Instrument Cluster)
PATS Type E (Powertrain Control Module)
PATS Type E (Powertrain Control Module)
PATS Type C (Instrument Cluster)
PATS Type E (Powertrain Control Module)
PATS Type E (Powertrain Control Module)
PATS Type B (Stand Alone PATS Module)
PATS Type E (Powertrain Control Module)
PATS Type E (Powertrain Control Module)
PATS Type E (Powertrain Control Module)
PATS Type E (Powertrain Control Module)
PATS Type C (Instrument Cluster)
PATS Type E (Powertrain Control Module)
PATS Type E (Powertrain Control Module)
PATS Type E (Powertrain Control Module)
PATS Type E (Powertrain Control Module)
PATS Type B (Stand Alone PATS Module)
PATS Type E (Powertrain Control Module)
PATS Type NA (No PATS)
PATS Type E (Powertrain Control Module)
PATS Type C (Instrument Cluster)
PATS Type E (Powertrain Control Module)
PATS Type E (Powertrain Control Module)
PATS Type F (Powertrain Control Module)
PATS Type E (Powertrain Control Module)
PATS Type C (Instrument Cluster)
PATS Type E (Powertrain Control Module)
PATS Type E (Powertrain Control Module)
PATS Type C (Instrument Cluster)
PATS Type E (Powertrain Control Module)
PATS Type E (Powertrain Control Module)
PATS Type E (Powertrain Control Module)
PATS Type E (Powertrain Control Module)
PATS Type C (Instrument Cluster)
PATS Type B (Stand Alone PATS Module)
PATS Type E (Powertrain Control Module)
PATS Type C (Powertrain Control Module)
PATS Type E (Powertrain Control Module)
PATS Type C (Instrument Cluster)
PATS Type E (Powertrain Control Module)
PATS Type A (Instrument Cluster)
PATS Type E (Powertrain Control Module)
PATS Type F (Powertrain Control Module)
PATS Type C (Instrument Cluster)
PATS Type C (Instrument Cluster)
PATS Type C (Instrument Cluster)
PATS Type E (Powertrain Control Module)
PATS Type E (Powertrain Control Module)
PATS Type E (Powertrain Control Module)
PATS Type E (Powertrain Control Module)
PATS Type E (Powertrain Control Module)
PATS Type E (Powertrain Control Module)
PATS Type C (Instrument Cluster)
PATS Type E (Powertrain Control Module)
PATS Type G (Instrument Cluster)
PATS Type E (Powertrain Control Module)
PATS Type A (Instrument Cluster)
Fleet Vehicles: PATS Type G (Instrument Cluster)
Non-Fleet Vehicles: PATS Type C (Instrument Cluster)
PATS Type C (Instrument Cluster)
PATS Type C (Instrument Cluster)
PATS Type C (Instrument Cluster)
PATS Type E (Powertrain Control Module)
PATS Type E (Powertrain Control Module)
PATS Type G (Instrument Cluster)
PATS Type C (Instrument Cluster)
PATS Type C (Instrument Cluster)
PATS Type C (Instrument Cluster)
PATS Type E (Powertrain Control Module)
PATS Type G (Instrument Cluster)
PATS Type C (Instrument Cluster)
PATS Type C (Instrument Cluster)
PATS Type E (Powertrain Control Module)
PATS Type A (Instrument Cluster)
PATS Type C (Instrument Cluster)
PATS Type C (Instrument Cluster)
PATS Type C (Instrument Cluster)
PATS Type C (Instrument Cluster)
PATS Type C (Instrument Cluster)
Fleet Vehicles: PATS Type G (Instrument Cluster)
Non-Fleet Vehicles: PATS Type C (Instrument Cluster)
PATS Type C (Instrument Cluster)
PATS Type C (Instrument Cluster)
PATS Type C (Instrument Cluster)
PATS Type C (Instrument Cluster)
PATS Type G (Instrument Cluster)
PATS Type C (Instrument Cluster)
PATS Type C (Instrument Cluster)
PATS Type C (Instrument Cluster)
PATS Type C (Instrument Cluster)
PATS Type E (Powertrain Control Module)
PATS Type G (Instrument Cluster)
PATS Type C (Instrument Cluster)
PATS Type C (Instrument Cluster)
PATS Type E (Powertrain Control Module)
PATS Type A (Instrument Cluster)
PATS Type C (Instrument Cluster)
PATS Type C (Instrument Cluster)
PATS Type C (Instrument Cluster)
Fleet Vehicles: PATS Type G (Instrument Cluster)
Non-Fleet Vehicles: PATS Type C (Instrument Cluster)
PATS Type C (Instrument Cluster)
PATS Type C (Instrument Cluster)
PATS Type C (Instrument Cluster)
PATS Type C (Instrument Cluster)
PATS Type G (Instrument Cluster)
PATS Type C (Instrument Cluster)
PATS Type C (Instrument Cluster)
PATS Type C (Instrument Cluster)
PATS Type C (Instrument Cluster)
PATS Type C (Instrument Cluster)
PATS Type C (Instrument Cluster)
PATS Type G (Instrument Cluster)
Keyed Ignition: PATS Type C (Instrument Cluster)
Push To Start: PATS Type C (Remote Function Actuator / Keyless Vehicle Module)
PATS Type A (Instrument Cluster)
PATS Type E (Powertrain Control Module)
PATS Type B (Body Control Module)
PATS Type C (Remote Function Actuator / Keyless Vehicle Module)
PATS Type C (Instrument Cluster)
PATS Type C (Instrument Cluster)
PATS Type C (Instrument Cluster)
PATS Type A (Instrument Cluster)
PATS Type C (Instrument Cluster)
PATS Type B (Body Control Module)
PATS Type B (Body Control Module)
PATS Type B (Body Control Module)
Keyed Ignition: PATS Type A (Instrument Cluster)
Push To Start: PATS Type C (Remote Function Actuator / Keyless Vehicle Module)
PATS Type C (Instrument Cluster)
PATS Type C (Instrument Cluster)
PATS Type C (Instrument Cluster)
PATS Type C (Instrument Cluster)
PATS Type C (Instrument Cluster)
Keyed Ignition: PATS Type C (Instrument Cluster)
Push To Start: PATS Type C (Remote Function Actuator / Keyless Vehicle Module)
PATS Type A (Instrument Cluster)
PATS Type E (Powertrain Control Module)
PATS Type B (Body Control Module)
PATS Type C (Remote Function Actuator / Keyless Vehicle Module)
PATS Type C (Instrument Cluster)
PATS Type C (Instrument Cluster)
PATS Type C (Instrument Cluster)
PATS Type A (Instrument Cluster)
PATS Type C (Instrument Cluster)
PATS Type B (Body Control Module)
PATS Type B (Body Control Module)
PATS Type B (Body Control Module)
Keyed Ignition: PATS Type A (Instrument Cluster)
Push To Start: PATS Type C (Remote Function Actuator / Keyless Vehicle Module)
PATS Type C (Instrument Cluster)
Keyed Ignition: PATS Type C (Instrument Cluster)
Push To Start: PATS Type C (Remote Function Actuator / Keyless Vehicle Module)
PATS Type C (Remote Function Actuator / Keyless Vehicle Module)
PATS Type C (Instrument Cluster)
PATS Type C (Instrument Cluster)
PATS Type C (Instrument Cluster)
Keyed Ignition: PATS Type C (Instrument Cluster)
Push To Start: PATS Type C (Remote Function Actuator / Keyless Vehicle Module)
PATS Type A (Instrument Cluster)
PATS Type B (Body Control Module)
PATS Type C (Remote Function Actuator / Keyless Vehicle Module)
PATS Type B (Body Control Module)
PATS Type C (Remote Function Actuator / Keyless Vehicle Module)
PATS Type B (Body Control Module)
PATS Type C (Remote Function Actuator / Keyless Vehicle Module)
PATS Type A (Instrument Cluster)
PATS Type C (Instrument Cluster)
PATS Type B (Body Control Module)
PATS Type B (Body Control Module)
PATS Type B (Body Control Module)
Keyed Ignition: PATS Type A (Instrument Cluster)
Push To Start: PATS Type C (Remote Function Actuator / Keyless Vehicle Module)
PATS Type B (Body Control Module)
PATS Type C (Remote Function Actuator / Keyless Vehicle Module)
Keyed Ignition: PATS Type C (Instrument Cluster)
Push To Start: PATS Type C (Remote Function Actuator / Keyless Vehicle Module)
PATS Type C (Remote Function Actuator / Keyless Vehicle Module)
PATS Type B (Body Control Module)
PATS Type B (Body Control Module)
PATS Type B (Body Control Module)
PATS Type C (Instrument Cluster)
Keyed Ignition: PATS Type C (Instrument Cluster)
Push To Start: PATS Type C (Remote Function Actuator / Keyless Vehicle Module)
PATS Type A (Instrument Cluster)
PATS Type B (Body Control Module)

In [12]:
# Split column 'Security' between 2 columns, where one column shows the PATS Type and the other one shows the PATS module location
df_ford[['PATS Type', 'PATS Module Location']] = df_ford['Security'].str.split('(', n=1, expand=True)

C:\Users\Weverson Barbieri\AppData\Local\Temp\ipykernel_9784\3384685316.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_ford[['PATS Type', 'PATS Module Location']] = df_ford['Security'].str.split('(', n=1, expand=True)
C:\Users\Weverson Barbieri\AppData\Local\Temp\ipykernel_9784\3384685316.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_ford[['PATS Type', 'PATS Module Location']] = df_ford['Security'].str.split('(', n=1, expand=True)

In [13]:
# Remove the ')' that remained at the values of the column 'PATS Module Location'
df_ford['PATS Module Location'] = df_ford['PATS Module Location'].str.strip(')')

C:\Users\Weverson Barbieri\AppData\Local\Temp\ipykernel_9784\370588408.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_ford['PATS Module Location'] = df_ford['PATS Module Location'].str.strip(')')

In [14]:
# Drop column security as its values were split in 2 columns
df_ford.drop(columns=['Security'])

,Year,Make,Model,ParameterReset,PATS Type,PATS Module Location
190,1996,Ford,Mustang,Parameter Reset Not Required,PATS Type A,Stand Alone PATS Module
191,1996,Ford,Taurus (Duratec & SHO only),Parameter Reset Not Required,PATS Type A,Stand Alone PATS Module
247,1997,Ford,Expedition,Parameter Reset Not Required,PATS Type A,Stand Alone PATS Module
248,1997,Ford,Mustang,Parameter Reset Not Required,PATS Type A,Stand Alone PATS Module
249,1997,Ford,Taurus (Duratec & SHO only),Parameter Reset Not Required,PATS Type A,Stand Alone PATS Module
...,...,...,...,...,...,...
3278,2013,Ford,FUSION EV,Parameter Reset Required,PATS Type B,Body Control Module
3279,2013,Ford,Mustang,Parameter Reset Required,PATS Type C,Instrument Cluster
3280,2013,Ford,Taurus,Parameter Reset Required,Keyed Ignition: PATS Type C,Instrument Cluster)\nPush To Start: PATS Type ...
3281,2013,Ford,TRANSIT CONNECT,Parameter Reset Required,PATS Type A,Instrument Cluster
3282,2013,Ford,TRANSIT,Parameter Reset Required,PATS Type B,Body Control Module

In [15]:
# Filter the models that has strings more than the PATS Type included in the row and drop column 'Security'
contour_info = df_ford[df_ford['Model'] == 'Contour (V6-only)'].drop(columns=['Security'])
contour_info_1998 = contour_info[contour_info['Year'] == 1998]

In [16]:
# Iterate in the PATS Module Location column of the Contour model to verify all strings available
for info in contour_info_1998['PATS Module Location']:
    print(info)

Stand Alone PATS Module)
Built February 2nd or later: PATS Type E (Powertrain Control Module

In [17]:
# Duplicate line '1998 Contour (V6-only)' between 2: 1998 Contour (V6-only) / Built >= February 2st and 1998 Contour (V6-only) / Built <= February 1st
contour_new1 = pd.DataFrame({'Year': [1998, 1998], 'Make': ['Ford', 'Ford'], 'Model': ['Contour (V6-only) / Built >= February 2st', 'Contour (V6-only) / Built <= February 1st'], 
                             'ParameterReset': ['Parameter Reset Not Required', 'Parameter Reset Not Required'], 'PATS Type': ['PATS Type E', 'PATS Type A'], 
                             'PATS Module Location': ['Powertrain Control Module', 'Powertrain Control Module']})

In [18]:
# Print the lines
contour_new1

,Year,Make,Model,ParameterReset,PATS Type,PATS Module Location
0,1998,Ford,Contour (V6-only) / Built >= February 2st,Parameter Reset Not Required,PATS Type E,Powertrain Control Module
1,1998,Ford,Contour (V6-only) / Built <= February 1st,Parameter Reset Not Required,PATS Type A,Powertrain Control Module

In [19]:
# Concatenate the new 2 lines to the main df and drop 'Security' column drop the old 1998 Contour (V6-only) line (index 325) and 
# store the updated df_ford into a new variable.
df_ford_new = pd.concat([df_ford, contour_new1]).drop(columns=['Security']).drop([325])
df_ford_new

,Year,Make,Model,ParameterReset,PATS Type,PATS Module Location
190,1996,Ford,Mustang,Parameter Reset Not Required,PATS Type A,Stand Alone PATS Module
191,1996,Ford,Taurus (Duratec & SHO only),Parameter Reset Not Required,PATS Type A,Stand Alone PATS Module
247,1997,Ford,Expedition,Parameter Reset Not Required,PATS Type A,Stand Alone PATS Module
248,1997,Ford,Mustang,Parameter Reset Not Required,PATS Type A,Stand Alone PATS Module
249,1997,Ford,Taurus (Duratec & SHO only),Parameter Reset Not Required,PATS Type A,Stand Alone PATS Module
...,...,...,...,...,...,...
3280,2013,Ford,Taurus,Parameter Reset Required,Keyed Ignition: PATS Type C,Instrument Cluster)\nPush To Start: PATS Type ...
3281,2013,Ford,TRANSIT CONNECT,Parameter Reset Required,PATS Type A,Instrument Cluster
3282,2013,Ford,TRANSIT,Parameter Reset Required,PATS Type B,Body Control Module
0,1998,Ford,Contour (V6-only) / Built >= February 2st,Parameter Reset Not Required,PATS Type E,Powertrain Control Module
1,1998,Ford,Contour (V6-only) / Built <= February 1st,Parameter Reset Not Required,PATS Type A,Powertrain Control Module

In [20]:
# Show the entire information the column contains
pd.set_option('display.max_colwidth', None)
# Iterate in the columns 'PATS Type' and 'PATS Module Location' and find the string 'Built'
for index, row in df_ford_new.iterrows():
    if 'Built' in row['PATS Type'] or 'Built' in row['PATS Module Location']:
        print(row)

Year                                                                                                               2001
Make                                                                                                               Ford
Model                                                                                              Explorer Sport (2dr)
ParameterReset                                                                                 Parameter Reset Required
PATS Type                                                                 Built July 23rd 2000 or Earlier: PATS Type B
PATS Module Location    Stand Alone PATS Module)\nBuilt July 24th 2000 or Later: PATS Type E (Powertrain Control Module
Name: 705, dtype: object
Year                                                                                                               2001
Make                                                                                                               Ford
Model                                                                                               Explorer Sport Trac
ParameterReset                                                                                 Parameter Reset Required
PATS Type                                                                 Built July 23rd 2000 or Earlier: PATS Type B
PATS Module Location    Stand Alone PATS Module)\nBuilt July 24th 2000 or Later: PATS Type E (Powertrain Control Module
Name: 706, dtype: object

In [21]:
# As the 'Explorer Sport (2dr) built <= July 23rd 2000 and the ones built >= July 24th 2000 are equipped with different PATS Types,
# separate those 2 different pats types in 2 columns and add at the end of the df_ford_new
df_ford_new.loc[len(df_ford_new.index)] = [2001, 'Ford', 'Explorer Sport (2dr) <= July 23rd 2000', 'Parameter Reset Required', 
                                           'PATS Type B', 'Stand Alone PATS Module']
df_ford_new.loc[len(df_ford_new.index)] = [2001, 'Ford', 'Explorer Sport (2dr) >= July 24th 2000', 'Parameter Reset Required', 
                                           'PATS Type E', 'Stand Alone PATS Module']

In [22]:
# Drop index 705, it was duplicated in 2 rows
df_ford_new.drop(index=705)

,Year,Make,Model,ParameterReset,PATS Type,PATS Module Location
190,1996,Ford,Mustang,Parameter Reset Not Required,PATS Type A,Stand Alone PATS Module
191,1996,Ford,Taurus (Duratec & SHO only),Parameter Reset Not Required,PATS Type A,Stand Alone PATS Module
247,1997,Ford,Expedition,Parameter Reset Not Required,PATS Type A,Stand Alone PATS Module
248,1997,Ford,Mustang,Parameter Reset Not Required,PATS Type A,Stand Alone PATS Module
249,1997,Ford,Taurus (Duratec & SHO only),Parameter Reset Not Required,PATS Type A,Stand Alone PATS Module
...,...,...,...,...,...,...
3282,2013,Ford,TRANSIT,Parameter Reset Required,PATS Type B,Body Control Module
0,1998,Ford,Contour (V6-only) / Built >= February 2st,Parameter Reset Not Required,PATS Type E,Powertrain Control Module
1,1998,Ford,Contour (V6-only) / Built <= February 1st,Parameter Reset Not Required,PATS Type A,Powertrain Control Module
265,2001,Ford,Explorer Sport (2dr) <= July 23rd 2000,Parameter Reset Required,PATS Type B,Stand Alone PATS Module
266,2001,Ford,Explorer Sport (2dr) >= July 24th 2000,Parameter Reset Required,PATS Type E,Stand Alone PATS Module

In [23]:
# Iterate into columns 'PATS Type" and 'PATS Module Location" and find the string 'Fleet Vehicles' 
for index, row in df_ford_new.iterrows():
    if 'Fleet Vehicles' in row['PATS Type'] or 'Fleet Vehicles' in row['PATS Module Location']:
        print(row)

Year                                                                                        2008
Make                                                                                        Ford
Model                                                                                   E-Series
ParameterReset                                                          Parameter Reset Required
PATS Type                                                           Fleet Vehicles: PATS Type G
PATS Module Location    Instrument Cluster)\nNon-Fleet Vehicles: PATS Type C (Instrument Cluster
Name: 2069, dtype: object
Year                                                                                        2009
Make                                                                                        Ford
Model                                                                                   E-Series
ParameterReset                                                          Parameter Reset Required
PATS Type                                                           Fleet Vehicles: PATS Type G
PATS Module Location    Instrument Cluster)\nNon-Fleet Vehicles: PATS Type C (Instrument Cluster
Name: 2316, dtype: object
Year                                                                                        2010
Make                                                                                        Ford
Model                                                                                   E-Series
ParameterReset                                                          Parameter Reset Required
PATS Type                                                           Fleet Vehicles: PATS Type G
PATS Module Location    Instrument Cluster)\nNon-Fleet Vehicles: PATS Type C (Instrument Cluster
Name: 2563, dtype: object

In [24]:
# As E-Series models fleet vehicles has PATS G and non-fleet vehicles has PATS C from 2008 to 2010, separate those 2 PATS types between 2 rows
# and add the new rows to the df_ford_new

# Fleet vehicles has PATS G from 2008 to 2010
df_ford_new.loc[len(df_ford_new.index)] = [2008, 'Ford', 'E-Series / Fleet Vehicles', 'Parameter Reset Required', 'PATS Type G', 'Instrument Cluster']
df_ford_new.loc[len(df_ford_new.index)] = [2009, 'Ford', 'E-Series / Fleet Vehicles', 'Parameter Reset Required', 'PATS Type G', 'Instrument Cluster']
df_ford_new.loc[len(df_ford_new.index)] = [2010, 'Ford', 'E-Series / Fleet Vehicles', 'Parameter Reset Required', 'PATS Type G', 'Instrument Cluster']

# Non-fleet vehicles has PATS C 2008 to 2010
df_ford_new.loc[len(df_ford_new.index)] = [2008, 'Ford', 'E-Series / non-Fleet Vehicles', 'Parameter Reset Required', 'PATS Type C', 'Instrument Cluster']
df_ford_new.loc[len(df_ford_new.index)] = [2009, 'Ford', 'E-Series / non-Fleet Vehicles', 'Parameter Reset Required', 'PATS Type C', 'Instrument Cluster']
df_ford_new.loc[len(df_ford_new.index)] = [2010, 'Ford', 'E-Series / non-Fleet Vehicles', 'Parameter Reset Required', 'PATS Type C', 'Instrument Cluster']

In [25]:
# Drop the old 2008 'E-Series, PATS G and C' based on the index rows 
df_ford_new.drop([2069, 2316, 2563])

,Year,Make,Model,ParameterReset,PATS Type,PATS Module Location
190,1996,Ford,Mustang,Parameter Reset Not Required,PATS Type A,Stand Alone PATS Module
191,1996,Ford,Taurus (Duratec & SHO only),Parameter Reset Not Required,PATS Type A,Stand Alone PATS Module
247,1997,Ford,Expedition,Parameter Reset Not Required,PATS Type A,Stand Alone PATS Module
248,1997,Ford,Mustang,Parameter Reset Not Required,PATS Type A,Stand Alone PATS Module
249,1997,Ford,Taurus (Duratec & SHO only),Parameter Reset Not Required,PATS Type A,Stand Alone PATS Module
...,...,...,...,...,...,...
268,2009,Ford,E-Series / Fleet Vehicles,Parameter Reset Required,PATS Type G,Instrument Cluster
269,2010,Ford,E-Series / Fleet Vehicles,Parameter Reset Required,PATS Type G,Instrument Cluster
270,2008,Ford,E-Series / non-Fleet Vehicles,Parameter Reset Required,PATS Type C,Instrument Cluster
271,2009,Ford,E-Series / non-Fleet Vehicles,Parameter Reset Required,PATS Type C,Instrument Cluster
272,2010,Ford,E-Series / non-Fleet Vehicles,Parameter Reset Required,PATS Type C,Instrument Cluster

In [26]:
# Iterate into columns 'PATS Type' and 'PATS Module Location' and find the string 'Push To Start: PATS Type C'
for index, row in df_ford_new.iterrows():
    if 'Push To Start: PATS Type C' in row['PATS Type'] or 'Push To Start: PATS Type C' in row['PATS Module Location']:
        print(row)

Year                                                                                                                  2010
Make                                                                                                                  Ford
Model                                                                                                               Taurus
ParameterReset                                                                                    Parameter Reset Required
PATS Type                                                                                     Keyed Ignition: PATS Type C
PATS Module Location    Instrument Cluster)\nPush To Start: PATS Type C (Remote Function Actuator / Keyless Vehicle Module
Name: 2576, dtype: object
Year                                                                                                                  2011
Make                                                                                                                  Ford
Model                                                                                                               FIESTA
ParameterReset                                                                                    Parameter Reset Required
PATS Type                                                                                     Keyed Ignition: PATS Type A
PATS Module Location    Instrument Cluster)\nPush To Start: PATS Type C (Remote Function Actuator / Keyless Vehicle Module
Name: 2806, dtype: object
Year                                                                                                                  2011
Make                                                                                                                  Ford
Model                                                                                                               Taurus
ParameterReset                                                                                    Parameter Reset Required
PATS Type                                                                                     Keyed Ignition: PATS Type C
PATS Module Location    Instrument Cluster)\nPush To Start: PATS Type C (Remote Function Actuator / Keyless Vehicle Module
Name: 2812, dtype: object
Year                                                                                                                  2012
Make                                                                                                                  Ford
Model                                                                                                               FIESTA
ParameterReset                                                                                    Parameter Reset Required
PATS Type                                                                                     Keyed Ignition: PATS Type A
PATS Module Location    Instrument Cluster)\nPush To Start: PATS Type C (Remote Function Actuator / Keyless Vehicle Module
Name: 3038, dtype: object
Year                                                                                                                  2012
Make                                                                                                                  Ford
Model                                                                                                                Focus
ParameterReset                                                                                    Parameter Reset Required
PATS Type                                                                                     Keyed Ignition: PATS Type C
PATS Module Location    Instrument Cluster)\nPush To Start: PATS Type C (Remote Function Actuator / Keyless Vehicle Module
Name: 3040, dtype: object
Year                                                                                                                  2012
Make                                                                                                                  Ford
Model                                                                                                               Taurus
ParameterReset                                                                                    Parameter Reset Required
PATS Type                                                                                     Keyed Ignition: PATS Type C
PATS Module Location    Instrument Cluster)\nPush To Start: PATS Type C (Remote Function Actuator / Keyless Vehicle Module
Name: 3045, dtype: object
Year                                                                                                                  2013
Make                                                                                                                  Ford
Model                                                                                                               FIESTA
ParameterReset                                                                                    Parameter Reset Required
PATS Type                                                                                     Keyed Ignition: PATS Type A
PATS Module Location    Instrument Cluster)\nPush To Start: PATS Type C (Remote Function Actuator / Keyless Vehicle Module
Name: 3271, dtype: object
Year                                                                                                                  2013
Make                                                                                                                  Ford
Model                                                                                                                Focus
ParameterReset                                                                                    Parameter Reset Required
PATS Type                                                                                     Keyed Ignition: PATS Type C
PATS Module Location    Instrument Cluster)\nPush To Start: PATS Type C (Remote Function Actuator / Keyless Vehicle Module
Name: 3274, dtype: object
Year                                                                                                                  2013
Make                                                                                                                  Ford
Model                                                                                                               Taurus
ParameterReset                                                                                    Parameter Reset Required
PATS Type                                                                                     Keyed Ignition: PATS Type C
PATS Module Location    Instrument Cluster)\nPush To Start: PATS Type C (Remote Function Actuator / Keyless Vehicle Module
Name: 3280, dtype: object

- The 'Push To Start' info, is mixed with the PATS module location and the PATS Type info is repeated in the 'PATS Type' column and in the 'PATS module location.
- These are the changes to be made:
    * Relocate the string 'Push To Start' to 'Model' column,
    * Remove the 'PATS Type C' from the 'Module Location' and leave this string only in the column 'PATS Type'
    * Split in 2 rows eg: 
        1th row: Taurus (Keyed Ignition), PATS module location = Instrument Cluster.
        2nd row: Taurus (Push To Start), PATS module location = Remote Function Actuator / Keyless Vehicle Module

In [27]:
# Add 1 new row for 2010 Taurus (Keyed Ignition)
df_ford_new.loc[len(df_ford_new.index)] = [2010, 'Ford', 'Taurus (Keyed Ignition)', 'Parameter Reset Required', 'PATS Type C', 'Instrument Cluster']

In [28]:
# Add 1 new row for 2010 Taurus (Push To Start)
df_ford_new.loc[len(df_ford_new.index)] = [2010, 'Ford', 'Taurus (Push To Start)', 'Parameter Reset Required', 'PATS Type C', 'Remote Function Actuator / Keyless Vehicle Module']

In [29]:
# Add 1 new row for 2011 FIESTA (Keyed Ignition)
df_ford_new.loc[len(df_ford_new.index)] = [2011, 'Ford', 'FIESTA (Keyed Ignition)', 'Parameter Reset Required', 'PATS Type A', 'Instrument Cluster']

In [30]:
# Add 1 new row for 2011 FIESTA (Push To Start)
df_ford_new.loc[len(df_ford_new.index)] = [2011, 'Ford', 'FIESTA (Push To Start)', 'Parameter Reset Required', 'PATS Type C', 'Remote Function Actuator / Keyless Vehicle Module']

In [31]:
# Add 1 new row for 2011 Taurus (Keyed Ignition)
df_ford_new.loc[len(df_ford_new.index)] = [2011, 'Ford', 'Taurus (Keyed Ignition)', 'Parameter Reset Required', 'PATS Type C', 'Instrument Cluster']

In [32]:
# Add 1 new row for 2011 Taurus (Push To Start)
df_ford_new.loc[len(df_ford_new.index)] = [2011, 'Ford', 'Taurus (Push To Start)', 'Parameter Reset Required', 'PATS Type C', 'Remote Function Actuator / Keyless Vehicle Module']

In [33]:
# As the first iteration to verify the word the string 'Push To Start: PATS Type C', iterate again to verify the more rows containing this string 
for index, row in df_ford_new.iterrows():
    if 'Push To Start: PATS Type C' in row['PATS Type'] or 'Push To Start: PATS Type C' in row['PATS Module Location']:
        print(row)

Year                                                                                                                  2010
Make                                                                                                                  Ford
Model                                                                                                               Taurus
ParameterReset                                                                                    Parameter Reset Required
PATS Type                                                                                     Keyed Ignition: PATS Type C
PATS Module Location    Instrument Cluster)\nPush To Start: PATS Type C (Remote Function Actuator / Keyless Vehicle Module
Name: 2576, dtype: object
Year                                                                                                                  2011
Make                                                                                                                  Ford
Model                                                                                                               FIESTA
ParameterReset                                                                                    Parameter Reset Required
PATS Type                                                                                     Keyed Ignition: PATS Type A
PATS Module Location    Instrument Cluster)\nPush To Start: PATS Type C (Remote Function Actuator / Keyless Vehicle Module
Name: 2806, dtype: object
Year                                                                                                                  2011
Make                                                                                                                  Ford
Model                                                                                                               Taurus
ParameterReset                                                                                    Parameter Reset Required
PATS Type                                                                                     Keyed Ignition: PATS Type C
PATS Module Location    Instrument Cluster)\nPush To Start: PATS Type C (Remote Function Actuator / Keyless Vehicle Module
Name: 2812, dtype: object
Year                                                                                                                  2012
Make                                                                                                                  Ford
Model                                                                                                               FIESTA
ParameterReset                                                                                    Parameter Reset Required
PATS Type                                                                                     Keyed Ignition: PATS Type A
PATS Module Location    Instrument Cluster)\nPush To Start: PATS Type C (Remote Function Actuator / Keyless Vehicle Module
Name: 3038, dtype: object
Year                                                                                                                  2012
Make                                                                                                                  Ford
Model                                                                                                                Focus
ParameterReset                                                                                    Parameter Reset Required
PATS Type                                                                                     Keyed Ignition: PATS Type C
PATS Module Location    Instrument Cluster)\nPush To Start: PATS Type C (Remote Function Actuator / Keyless Vehicle Module
Name: 3040, dtype: object
Year                                                                                                                  2012
Make                                                                                                                  Ford
Model                                                                                                               Taurus
ParameterReset                                                                                    Parameter Reset Required
PATS Type                                                                                     Keyed Ignition: PATS Type C
PATS Module Location    Instrument Cluster)\nPush To Start: PATS Type C (Remote Function Actuator / Keyless Vehicle Module
Name: 3045, dtype: object
Year                                                                                                                  2013
Make                                                                                                                  Ford
Model                                                                                                               FIESTA
ParameterReset                                                                                    Parameter Reset Required
PATS Type                                                                                     Keyed Ignition: PATS Type A
PATS Module Location    Instrument Cluster)\nPush To Start: PATS Type C (Remote Function Actuator / Keyless Vehicle Module
Name: 3271, dtype: object
Year                                                                                                                  2013
Make                                                                                                                  Ford
Model                                                                                                                Focus
ParameterReset                                                                                    Parameter Reset Required
PATS Type                                                                                     Keyed Ignition: PATS Type C
PATS Module Location    Instrument Cluster)\nPush To Start: PATS Type C (Remote Function Actuator / Keyless Vehicle Module
Name: 3274, dtype: object
Year                                                                                                                  2013
Make                                                                                                                  Ford
Model                                                                                                               Taurus
ParameterReset                                                                                    Parameter Reset Required
PATS Type                                                                                     Keyed Ignition: PATS Type C
PATS Module Location    Instrument Cluster)\nPush To Start: PATS Type C (Remote Function Actuator / Keyless Vehicle Module
Name: 3280, dtype: object

In [34]:
# Add 1 new row for 2012 FIESTA (Keyed Ignition) PATS Type A
df_ford_new.loc[len(df_ford_new.index)] = [2012, 'Ford', 'FIESTA (Keyed Ignition)', 'Parameter Reset Required', 'PATS Type A', 'Instrument Cluster']

In [35]:
# Add 1 new row for 2012 FIESTA (Push To Start) PATS Type C
df_ford_new.loc[len(df_ford_new.index)] = [2012, 'Ford', 'FIESTA (Push To Start)', 'Parameter Reset Required', 'PATS Type C', 'Remote Function Actuator / Keyless Vehicle Module']

In [36]:
# Add 1 new row for 2012 Focus (Keyed Ignition)
df_ford_new.loc[len(df_ford_new.index)] = [2012, 'Ford', 'Focus (Keyed Ignition)', 'Parameter Reset Required', 'PATS Type C', 'Instrument Cluster']

In [37]:
# Add 1 new row for 2012 Focus (Push To Start)
df_ford_new.loc[len(df_ford_new.index)] = [2012, 'Ford', 'Focus (Push To Start)', 'Parameter Reset Required', 'PATS Type C', 'Remote Function Actuator / Keyless Vehicle Module']

In [38]:
# Add 1 new row for 2012 Taurus (Keyed Ignition)
df_ford_new.loc[len(df_ford_new.index)] = [2012, 'Ford', 'Taurus (Keyed Ignition)', 'Parameter Reset Required', 'PATS Type C', 'Instrument Cluster']

In [39]:
# Add 1 new row for 2012 Taurus (Push To Start)
df_ford_new.loc[len(df_ford_new.index)] = [2012, 'Ford', 'Taurus (Push To Start)', 'Parameter Reset Required', 'PATS Type C', 'Remote Function Actuator / Keyless Vehicle Module']

In [40]:
# As the first iteration to verify the string 'Push To Start: PATS Type C', iterate again to verify the more rows containing this string 
for index, row in df_ford_new.iterrows():
    if 'Push To Start: PATS Type C' in row['PATS Type'] or 'Push To Start: PATS Type C' in row['PATS Module Location']:
        print(row)

Year                                                                                                                  2010
Make                                                                                                                  Ford
Model                                                                                                               Taurus
ParameterReset                                                                                    Parameter Reset Required
PATS Type                                                                                     Keyed Ignition: PATS Type C
PATS Module Location    Instrument Cluster)\nPush To Start: PATS Type C (Remote Function Actuator / Keyless Vehicle Module
Name: 2576, dtype: object
Year                                                                                                                  2011
Make                                                                                                                  Ford
Model                                                                                                               FIESTA
ParameterReset                                                                                    Parameter Reset Required
PATS Type                                                                                     Keyed Ignition: PATS Type A
PATS Module Location    Instrument Cluster)\nPush To Start: PATS Type C (Remote Function Actuator / Keyless Vehicle Module
Name: 2806, dtype: object
Year                                                                                                                  2011
Make                                                                                                                  Ford
Model                                                                                                               Taurus
ParameterReset                                                                                    Parameter Reset Required
PATS Type                                                                                     Keyed Ignition: PATS Type C
PATS Module Location    Instrument Cluster)\nPush To Start: PATS Type C (Remote Function Actuator / Keyless Vehicle Module
Name: 2812, dtype: object
Year                                                                                                                  2012
Make                                                                                                                  Ford
Model                                                                                                               FIESTA
ParameterReset                                                                                    Parameter Reset Required
PATS Type                                                                                     Keyed Ignition: PATS Type A
PATS Module Location    Instrument Cluster)\nPush To Start: PATS Type C (Remote Function Actuator / Keyless Vehicle Module
Name: 3038, dtype: object
Year                                                                                                                  2012
Make                                                                                                                  Ford
Model                                                                                                                Focus
ParameterReset                                                                                    Parameter Reset Required
PATS Type                                                                                     Keyed Ignition: PATS Type C
PATS Module Location    Instrument Cluster)\nPush To Start: PATS Type C (Remote Function Actuator / Keyless Vehicle Module
Name: 3040, dtype: object
Year                                                                                                                  2012
Make                                                                                                                  Ford
Model                                                                                                               Taurus
ParameterReset                                                                                    Parameter Reset Required
PATS Type                                                                                     Keyed Ignition: PATS Type C
PATS Module Location    Instrument Cluster)\nPush To Start: PATS Type C (Remote Function Actuator / Keyless Vehicle Module
Name: 3045, dtype: object
Year                                                                                                                  2013
Make                                                                                                                  Ford
Model                                                                                                               FIESTA
ParameterReset                                                                                    Parameter Reset Required
PATS Type                                                                                     Keyed Ignition: PATS Type A
PATS Module Location    Instrument Cluster)\nPush To Start: PATS Type C (Remote Function Actuator / Keyless Vehicle Module
Name: 3271, dtype: object
Year                                                                                                                  2013
Make                                                                                                                  Ford
Model                                                                                                                Focus
ParameterReset                                                                                    Parameter Reset Required
PATS Type                                                                                     Keyed Ignition: PATS Type C
PATS Module Location    Instrument Cluster)\nPush To Start: PATS Type C (Remote Function Actuator / Keyless Vehicle Module
Name: 3274, dtype: object
Year                                                                                                                  2013
Make                                                                                                                  Ford
Model                                                                                                               Taurus
ParameterReset                                                                                    Parameter Reset Required
PATS Type                                                                                     Keyed Ignition: PATS Type C
PATS Module Location    Instrument Cluster)\nPush To Start: PATS Type C (Remote Function Actuator / Keyless Vehicle Module
Name: 3280, dtype: object

In [41]:
# Add 1 new row for 2013 FIESTA (Keyed Ignition) and PATS Type A
df_ford_new.loc[len(df_ford_new.index)] = [2013, 'Ford', 'FIESTA (Keyed Ignition)', 'Parameter Reset Required', 'PATS Type A', 'Instrument Cluster']

In [42]:
# Add 1 new row for 2013 FIESTA (Push To Start)
df_ford_new.loc[len(df_ford_new.index)] = [2013, 'Ford', 'FIESTA (Push To Start)', 'Parameter Reset Required', 'PATS Type C', 'Instrument Cluster']

In [243]:
# Add 1 new row for 2013 Focus (Keyed Ignition)
df_ford_new.loc[len(df_ford_new.index)] = [2013, 'Ford', 'Focus (Keyed Ignition)', 'Parameter Reset Required', 'PATS Type C', 'Instrument Cluster']

In [43]:
# Add 1 new row for 2013 Focus (Push To Start)
df_ford_new.loc[len(df_ford_new.index)] = [2013, 'Ford', 'Focus (Push To Start)', 'Parameter Reset Required', 'PATS Type C', 'Instrument Cluster']

In [44]:
# Add 1 new row for 2013 Taurus (Keyed Ignition)
df_ford_new.loc[len(df_ford_new.index)] = [2013, 'Ford', 'Taurus (Keyed Ignition)', 'Parameter Reset Required', 'PATS Type C', 'Instrument Cluster']

In [45]:
# Add 1 new row for 2013 Taurus (Push To Start)
df_ford_new.loc[len(df_ford_new.index)] = [2013, 'Ford', 'Taurus (Push To Start)', 'Parameter Reset Required', 'PATS Type C', 'Instrument Cluster']

In [46]:
# Create a list to store the indexes
df_ford_indexes_to_drop = []

# Iterate in the column 'PATS Module Location' and store the indexes from the rows 
# containing the string 'Instrument Cluster)\nPush To Start: PATS Type C (Remote Function Actuator / Keyless Vehicle Module'
for index, value in df_ford_new['PATS Module Location'].items():
    if value == 'Instrument Cluster)\nPush To Start: PATS Type C (Remote Function Actuator / Keyless Vehicle Module':
        df_ford_indexes_to_drop.append(index)

# Print the indexes
print(df_ford_indexes_to_drop)

[2576, 2806, 2812, 3038, 3040, 3045, 3271, 3274, 3280]

In [47]:
# Drop all old rows after splitting between 'keyed ignition' and 'push to start' configuration
df_ford_updated = df_ford_new.drop([2576, 2806, 2812, 3038, 3040, 3045, 3271, 3274, 3280])

In [48]:
# Verify if there are rows containing the string 'Push To Start: PATS Type C' 
for index, row in df_ford_updated.iterrows():
    if 'Push To Start: PATS Type C' in row['PATS Type'] or 'Push To Start: PATS Type C' in row['PATS Module Location']:
        print(row)

In [8]:
# Filter only rows from make "Lincoln" to manipulate the data
df_lincoln = df[df['Make'] == 'Lincoln']

In [9]:
# Split column 'Security' between 2 columns, where one column shows the PATS Type and the other one shows the PATS module location
df_lincoln[['PATS Type', 'PATS Module Location']] = df_lincoln['Security'].str.split('(', n=1, expand=True)

C:\Users\Weverson Barbieri\AppData\Local\Temp\ipykernel_23156\2886703368.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_lincoln[['PATS Type', 'PATS Module Location']] = df_lincoln['Security'].str.split('(', n=1, expand=True)
C:\Users\Weverson Barbieri\AppData\Local\Temp\ipykernel_23156\2886703368.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_lincoln[['PATS Type', 'PATS Module Location']] = df_lincoln['Security'].str.split('(', n=1, expand=True)

In [10]:
# Drop column security as its values were split in 2 columns
df_lincoln_new = df_lincoln.drop(columns=['Security'])

In [11]:
# Remove the ')' that remained at the values of the column 'PATS Module Location'
df_lincoln_new['PATS Module Location'] = df_lincoln_new['PATS Module Location'].str.strip(')')

In [12]:
# The model 'Keyed Ignition:' and 'Push To Start:' confuguration are located in the same rows.
# Identifies which rows have the strings 'Keyed Ignition:' and 'Push To Start:' to separate them in 2 rows.
# Iterates in the column 'PATS Type' and bring the rows which contains the strings 'Keyed Ignition:'
for index, row in df_lincoln_new.iterrows():
    if 'Keyed Ignition:' in row['PATS Type']:
        print(row)

Year                                                                 2009
Make                                                              Lincoln
Model                                                                 MKS
ParameterReset                                   Parameter Reset Required
PATS Type                                    Keyed Ignition: PATS Type C
PATS Module Location    Instrument Cluster)\nPush To Start: PATS Type ...
Name: 2384, dtype: object
Year                                                                 2010
Make                                                              Lincoln
Model                                                                 MKS
ParameterReset                                   Parameter Reset Required
PATS Type                                    Keyed Ignition: PATS Type C
PATS Module Location    Instrument Cluster)\nPush To Start: PATS Type ...
Name: 2630, dtype: object
Year                                                                 2011
Make                                                              Lincoln
Model                                                                 MKS
ParameterReset                                   Parameter Reset Required
PATS Type                                    Keyed Ignition: PATS Type C
PATS Module Location    Instrument Cluster)\nPush To Start: PATS Type ...
Name: 2862, dtype: object
Year                                                                 2012
Make                                                              Lincoln
Model                                                                 MKS
ParameterReset                                   Parameter Reset Required
PATS Type                                    Keyed Ignition: PATS Type C
PATS Module Location    Instrument Cluster)\nPush To Start: PATS Type ...
Name: 3098, dtype: object

In [13]:
# Separate in 2 lines the 'Keyed Ignition' configuration and 'Push To Start" configuration.
df_lincoln_new.loc[len(df_lincoln_new.index)] = [2009, 'Lincoln', 'MKS (Keyed Ignition)', 'Parameter Reset Required', 'PATS Type C', 'Instrument Cluster']
df_lincoln_new.loc[len(df_lincoln_new.index)] = [2009, 'Lincoln', 'MKS (Push To Start)', 'Parameter Reset Required', 'PATS Type C', 'Remote Function Actuator / Keyless Vehicle Module']
df_lincoln_new.loc[len(df_lincoln_new.index)] = [2010, 'Lincoln', 'MKS (Keyed Ignition)', 'Parameter Reset Required', 'PATS Type C', 'Instrument Cluster']
df_lincoln_new.loc[len(df_lincoln_new.index)] = [2010, 'Lincoln', 'MKS (Push To Start)', 'Parameter Reset Required', 'PATS Type C', 'Remote Function Actuator / Keyless Vehicle Module']
df_lincoln_new.loc[len(df_lincoln_new.index)] = [2011, 'Lincoln', 'MKS (Keyed Ignition)', 'Parameter Reset Required', 'PATS Type C', 'Instrument Cluster']
df_lincoln_new.loc[len(df_lincoln_new.index)] = [2011, 'Lincoln', 'MKS (Push To Start)', 'Parameter Reset Required', 'PATS Type C', 'Remote Function Actuator / Keyless Vehicle Module']
df_lincoln_new.loc[len(df_lincoln_new.index)] = [2012, 'Lincoln', 'MKS (Keyed Ignition)', 'Parameter Reset Required', 'PATS Type C', 'Instrument Cluster']
df_lincoln_new.loc[len(df_lincoln_new.index)] = [2012, 'Lincoln', 'MKS (Push To Start)', 'Parameter Reset Required', 'PATS Type C', 'Remote Function Actuator / Keyless Vehicle Module']

In [14]:
# Iterate in the new data (after new lines included) to get all index numbers containing the string 'Keyed Ignition'
for index, row in df_lincoln_new.iterrows():
    if 'Keyed Ignition' in row['PATS Type']:
        print(index)

2384
2630
2862
3098

In [15]:
# Drop all old rows after splitting between 'keyed ignition' and 'push to start' configuration
df_lincoln_new.drop([2384, 2630, 2862, 3098])

,Year,Make,Model,ParameterReset,PATS Type,PATS Module Location
267,1997,Lincoln,Mark VIII,Parameter Reset Not Required,PATS Type D,Steering Column Ignition Lock Module
360,1998,Lincoln,Continental,Parameter Reset Required,PATS Type C,Instrument Cluster
361,1998,Lincoln,Mark VIII,Parameter Reset Not Required,PATS Type D,Steering Column Ignition Lock Module
362,1998,Lincoln,Navigator,Parameter Reset Not Required,PATS Type A,Stand Alone PATS Module
363,1998,Lincoln,Town Car,Parameter Reset Required,PATS Type C,Instrument Cluster
...,...,...,...,...,...,...
82,2010,Lincoln,MKS (Push To Start),Parameter Reset Required,PATS Type C,Remote Function Actuator / Keyless Vehicle Module
83,2011,Lincoln,MKS (Keyed Ignition),Parameter Reset Required,PATS Type C,Instrument Cluster
84,2011,Lincoln,MKS (Push To Start),Parameter Reset Required,PATS Type C,Remote Function Actuator / Keyless Vehicle Module
85,2012,Lincoln,MKS (Keyed Ignition),Parameter Reset Required,PATS Type C,Instrument Cluster
86,2012,Lincoln,MKS (Push To Start),Parameter Reset Required,PATS Type C,Remote Function Actuator / Keyless Vehicle Module

In [16]:
# Concatenate both new dataframes after manipulating the data and making some changes
df_lincoln_updated = pd.concat([df_lincoln_new, df_lincoln_new])

In [200]:
# Filter the df by based on the Mercury into a varible to analyse a manipulate the data
df_mercury = df[df['Make'] == 'Mercury']

In [201]:
# Split the 'Security' column in 2 columns to separate the Pats module location and the pats type
df_mercury[['PATS Type', 'PATS Module Location']] = df_mercury['Security'].str.split('(', n=1, expand=True)

C:\Users\Weverson Barbieri\AppData\Local\Temp\ipykernel_3336\3965777578.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_mercury[['PATS Type', 'PATS Module Location']] = df_mercury['Security'].str.split('(', n=1, expand=True)
C:\Users\Weverson Barbieri\AppData\Local\Temp\ipykernel_3336\3965777578.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_mercury[['PATS Type', 'PATS Module Location']] = df_mercury['Security'].str.split('(', n=1, expand=True)

In [202]:
# Remove the caractere ')' from all rows in the column 'PATS Module Location'
df_mercury['PATS Module Location'] = df_mercury['PATS Module Location'].str.strip(')')

C:\Users\Weverson Barbieri\AppData\Local\Temp\ipykernel_3336\4086986821.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_mercury['PATS Module Location'] = df_mercury['PATS Module Location'].str.strip(')')

In [203]:
# Drop the column 'Security'. The info split into 2 columns
df_mercury_dropped_security = df_mercury.drop(columns=['Security'])

Only the index 370 model Mystique (V-6 only) should be split in 2 columns. Models built February 1st 1998 or Earlier are equipped with PATS Type A and the models Built February 2nd 1998 or Later, are equipped with PATS Type E. Also, the module location are different as well.

In [204]:
# Add 2 lines to separate the model 'Mystique (V-6 only)' in 2 rows: built < February 1st 1998 or Earlier and built > February 2nd 1998 or Later   Contour (V6-only) / Built >= February 2st
df_mercury_dropped_security.loc[len(df_mercury.index)] = [1998, 'Mercury', 'Mystique (V-6 only) / Built <= February 1st', 'Parameter Reset Not Required', 'PATS Type A', 'Stand Alone PATS Module']
df_mercury_dropped_security.loc[len(df_mercury.index)] = [1998, 'Mercury', 'Mystique (V-6 only) / Built >= February 2nd', 'Parameter Reset Not Required', 'PATS Type E', 'Powertrain Control Module']

In [205]:
# Drop index 370 containing the old info
df_mercury_updated = df_mercury_dropped_security.drop([370])

In [206]:
# Filter the Mazda and store into a variable
df_mazda = df[df['Make'] == 'Mazda']

In [207]:
# Create a list to store the rows with caractere \n
mazda_caractere_list = []
# Create a list to store the indexes to be removed 
mazda_caractere_index_list = []

# Loop in the lines of the df_mazda to find the caractere \n
for index, row in df_mazda.iterrows():
    # Condition when finding '\n' in the rows of column 'Security'
    if '\n' in row['Security']:
        # Store the rows with the said caractere in the list 
        mazda_caractere_list.append(row)
        # Store the indexes numbers containing the said caractere
        mazda_caractere_index_list.append(index)

# Change 'mazda_caractere_list' to dataframe
df_mazda_w_caract = pd.DataFrame(mazda_caractere_list)

In [208]:
# Check if the df is correct
df_mazda_w_caract.head()

,Year,Make,Model,Security,ParameterReset
1670,2006,Mazda,Mazda6,Keyed Ignition: M-B\nAdvanced Keyless: M-D,Parameter Reset Not Required
1672,2006,Mazda,MX-5 (Miata),Advanced Keyless Entry w/ Keyless Start): M-D\nKeyless Entry w/ Keyed Ignition: M-C,Parameter Reset Required
1673,2006,Mazda,RX-8,Keyed Ignition: M-C\nAdvanced Keyless: M-D,Parameter Reset Required
1899,2007,Mazda,CX-7,Keyed Ignition: M-C\nAdvanced Keyless: MD,Parameter Reset Required
1900,2007,Mazda,CX-9,Keyed Ignition: M-C\nAdvanced Keyless: M-D,Parameter Reset Required

In [209]:
# Split the security types in 2 lines (keeping year/model), using the caractere '\n' as delimiter
df_mazda_w_caract = df_mazda_w_caract.assign(Security=df_mazda_w_caract['Security'].str.split('\n')).explode('Security')

In [210]:
# Clear the df_mazda by removing the rows containing the caractere '\n' based on the index list
df_mazda = df_mazda.drop(index=mazda_caractere_index_list)

In [211]:
# Concatenate the dataframe after splitting lines with the main df_mazda
df_mazda_updated = pd.concat([df_mazda_w_caract, df_mazda])

In [212]:
# Sort the dataframe using the column 'Year' and reset index
df_mazda_updated = df_mazda_updated.sort_values(['Year']).reset_index().drop(columns=['index'])

In [213]:
# Explode column 'Security' to create new lines
# df_mazda_updated = df_mazda.explode('Security')

In [214]:
# Create a new dataframe containing only Chevrolet: 'Chevrolet', 'Pontiac', 'Cadillac', 'Buick', 'Oldsmobile', 'GMC', 'Saturn', 'Hummer'
chevrolet_list = ['Chevrolet', 'Pontiac', 'Cadillac', 'Buick', 'Oldsmobile', 'GMC', 'Saturn', 'Hummer']

In [215]:
# Create a dataframe containing only chevrolet brands 
df_chevrolet = df[df['Make'].isin(chevrolet_list)]

In [216]:
df_chevrolet

      Year       Make         Model         Security ParameterReset
0     1986  Chevrolet      Corvette             VATS            NaN
1     1987  Chevrolet      Corvette             VATS            NaN
2     1988  Chevrolet      Corvette             VATS            NaN
3     1988    Pontiac      Firebird        GTA\nonly            NaN
4     1989   Cadillac       Allante              PK1            NaN
...    ...        ...           ...              ...            ...
3284  2013        GMC        Savana             PK3+            NaN
3285  2013        GMC        Sierra             PK3+            NaN
3286  2013        GMC      Yukon XL             PK3+            NaN
3287  2013        GMC  Yukon/Denali             PK3+            NaN
3288  2013        GMC       Terrain  PK3+\nSmart Key            NaN

[663 rows x 5 columns]

In [217]:
# Drop the column 'ParameterReset' as it is not applicable to Chevrolet
df_chevrolet_dropped_column = df_chevrolet.drop(columns=['ParameterReset'])

In [218]:
# Rename column 'Security'
df_chevrolet_dropped_column.rename(columns={'Security': 'Security Type'})

      Year       Make         Model    Security Type
0     1986  Chevrolet      Corvette             VATS
1     1987  Chevrolet      Corvette             VATS
2     1988  Chevrolet      Corvette             VATS
3     1988    Pontiac      Firebird        GTA\nonly
4     1989   Cadillac       Allante              PK1
...    ...        ...           ...              ...
3284  2013        GMC        Savana             PK3+
3285  2013        GMC        Sierra             PK3+
3286  2013        GMC      Yukon XL             PK3+
3287  2013        GMC  Yukon/Denali             PK3+
3288  2013        GMC       Terrain  PK3+\nSmart Key

[663 rows x 4 columns]

A column name 'Is this hardware clonable' will be included in the Chevrolet dataframe to show which hardwares are clonable based on the part number. As the hardware part numbers are not available and their values will need to be added manually, these are the next steps to add the hardware part numbers:
1. Download the 'df_chevrolet_dropped_column' in excel format.
2. Add the hardware part numbers manually from the GM compatibility chart.
3. Fill out the column 'Is this hardware clonable' rows comparing the 'df_chevrolet_dropped_column' with the 'List of Cloneable Modules'.

In [278]:
# Download the dateframe 'chevrolet_list_filtered' in xlsx format and name the file 'chevrolet_hardware_list
# df_chevrolet_dropped_column.to_excel('chevrolet_hardware_list.xlsx', index=False)

In [219]:
# Load the xlsx file containing the dataframe after adding the hardware part numbers
df_chevrolet = pd.read_excel('C:\Language_Projects\Language_Projects\Python\Flagship_1\Immo_Assistant.app\data\chevrolet_hardware_list.xlsx')

<>:2: SyntaxWarning: invalid escape sequence '\L'
<>:2: SyntaxWarning: invalid escape sequence '\L'
C:\Users\Weverson Barbieri\AppData\Local\Temp\ipykernel_3336\394097893.py:2: SyntaxWarning: invalid escape sequence '\L'
  df_chevrolet = pd.read_excel('C:\Language_Projects\Language_Projects\Python\Flagship_1\Immo_Assistant.app\data\chevrolet_hardware_list.xlsx')

In [220]:
df_chevrolet.head()

   Year       Make     Model   Security       hardware_part_number
0  1986  Chevrolet  Corvette       VATS  Information not available
1  1987  Chevrolet  Corvette       VATS  Information not available
2  1988  Chevrolet  Corvette       VATS  Information not available
3  1988    Pontiac  Firebird  GTA\nonly  Information not available
4  1989   Cadillac   Allante        PK1  Information not available

In [221]:
# Load the xlsx file containing the clonable hardware part numbers   
list_clonable_modules = pd.read_excel('C:\Language_Projects\Language_Projects\Python\Flagship_1\Immo_Assistant.app\data\List of Clonable Modules.xlsx')

<>:2: SyntaxWarning: invalid escape sequence '\L'
<>:2: SyntaxWarning: invalid escape sequence '\L'
C:\Users\Weverson Barbieri\AppData\Local\Temp\ipykernel_3336\1625161208.py:2: SyntaxWarning: invalid escape sequence '\L'
  list_clonable_modules = pd.read_excel('C:\Language_Projects\Language_Projects\Python\Flagship_1\Immo_Assistant.app\data\List of Clonable Modules.xlsx')

In [222]:
# Show all columns of the dataframe
list_clonable_modules.columns

Index(['Cloning Tools', 'ECM Hardware', 'cloning_status', 'ECU Brand', 'Year',
       'Year/Model/Engine Size/HP', 'Manufacturer', 'Vehicle Type', 'Notes'],
      dtype='object')

In [223]:
# Drop most columns and leave only 2 columns named: 'ECM Hardware' and 'cloning_status' and store in a variable
list_clonable_modules_updated = list_clonable_modules.drop(columns=['Cloning Tools', 'ECU Brand', 'Year', 'Year/Model/Engine Size/HP', 'Manufacturer', 'Vehicle Type', 'Notes'])

In [224]:
# Print the first rows on the dataframe updated
list_clonable_modules_updated.head()

  ECM Hardware      cloning_status
0     E83 (GM)  Currently possible
1     E78 (GM)  Currently possible
2     E87 (GM)  Currently possible
3     E39 (GM)  Currently possible
4    E39A (GM)  Currently possible

In [225]:
# Filter the hardware pn# that can be clonable
list_clonable_modules_filtered = list_clonable_modules_updated[list_clonable_modules_updated['cloning_status'] == 'Currently possible']

In [226]:
# Create a list to store the hardwares prefixes got from the clonable list
clonable_modules_list = []

# Iterate in the column 'ECM Hardware' to get their prefixes
for part_number in list_clonable_modules_filtered['ECM Hardware']:
    ecm_hardware_prefix = part_number.split(' ')[0]
    clonable_modules_list.append(ecm_hardware_prefix)

In [227]:
# Print the last rows on the dataframe containing the hardware part number values
df_chevrolet.tail()

     Year Make         Model         Security       hardware_part_number
657  2013  GMC        Savana             PK3+                    E38-AK8
658  2013  GMC        Sierra             PK3+                    E86-A24
659  2013  GMC      Yukon XL             PK3+  Information not available
660  2013  GMC  Yukon Denali             PK3+                    E38-AK8
661  2013  GMC       Terrain  PK3+\nSmart Key                  E39A-H98S

In [228]:
# Create a list to store hardware prefixes
hardware_prefix_list = []

# Iterate into the main dataframe to get the prefixes 
for hardware_pn in df_chevrolet['hardware_part_number']:
    hardware_prefix = hardware_pn.split('-')[0] # [0] indicates the first part of the list where the string needed is located, eg: 'E39', 'E38', etc.
    hardware_prefix_list.append(hardware_prefix)
    
# Add a new column contaning the prefixes
df_chevrolet['hardware_prefix'] = hardware_prefix_list

In [229]:
# Create a list to store the the string "Yes" or "No"
hardware_clonable_list = []
# Variable containing the string "Yes" to be used when a given part number is in the clonable_modules_list
yes_clonable = 'Yes'
# Variable containing the string "No" to be used when a given part number IS NOT in the clonable_modules_list
not_clonable = 'No'
# Loop in the 'hardware_prefix' column to check whether or not the part numbers are clonable 
for hardware_pn in df_chevrolet['hardware_prefix']:
    if hardware_pn in clonable_modules_list:
        hardware_clonable_list.append(yes_clonable)
    else:
        hardware_clonable_list.append(not_clonable)

# Create a new column after confirming the part numbers are clonable or not 
df_chevrolet['Is this hardware clonable?'] = hardware_clonable_list

In [230]:
# Drop column 'hardware_prefix' as it was used only to confirm the clonable hardwares
df_chevrolet_dropped_hardwarepre = df_chevrolet.drop(columns='hardware_prefix')

* CREATING SEPARATE DATAFRAMES FOR EACH MAKE:
 
The intended application will use the streamlit library to show the makes available and their security system information. As most makes have different security system and information-related, it is needed to create separate Dataframes for all/most of them. 

For instance, Ford vehicles requires parameter reset and there is a column showing whether or not this procedure is required. However, Chevrolet vehicles requires a different procedure and some hardwares can be cloned. That is, Ford and Chevrolet vehicles do not match the security information-related. The solution for this will be to create separate Dataframes for all makes.

In [231]:
# Show all makes under Chevrolet and use this list to guide when creating separate Dataframes
df_chevrolet_dropped_hardwarepre['Make'].unique()

array(['Chevrolet', 'Pontiac', 'Cadillac', 'Buick', 'Oldsmobile', 'GMC',
       'Saturn', 'Hummer'], dtype=object)

In [232]:
# Rename the column 'hardware_part_number' to 'Hardware Part Number'
df_chevrolet_renamed_column = df_chevrolet_dropped_hardwarepre.rename(columns={'hardware_part_number':'Hardware Part Number'})

In [233]:
# Create a dataframe only with Make: Chevrolet
df_chevy_filtered = df_chevrolet_renamed_column[df_chevrolet_renamed_column['Make'] == 'Chevrolet']

In [234]:
# Check is the df is ok
df_chevy_filtered.tail()

,Year,Make,Model,Security,Hardware Part Number,Is this hardware clonable?
651,2013,Chevrolet,Malibu,PK3+\nSmart Key,E39A-H98S,Yes
652,2013,Chevrolet,Sonic,PK3+\nSmart Key,E78-AB8,Yes
653,2013,Chevrolet,Spark,PK3+\nSmart Key,E83,Yes
654,2013,Chevrolet,Cruze,PK3+\nSmart Key,E78-AB8,Yes
655,2013,Chevrolet,Volt,PK3+\nSmart Key,E78-AB8,Yes

In [235]:
# Create a dataframe only with Make: Pontiac
df_pontiac = df_chevrolet_renamed_column[df_chevrolet_renamed_column['Make'] == 'Pontiac']

In [236]:
# Check is the df is ok
df_pontiac.tail()

,Year,Make,Model,Security,Hardware Part Number,Is this hardware clonable?
514,2009,Pontiac,Vibe,Toyota\nImmobilizer,Information not available,No
554,2010,Pontiac,G3,Opt,Information not available,No
555,2010,Pontiac,G6,PK3+,Information not available,No
556,2010,Pontiac,G8,PK3+,Information not available,No
557,2010,Pontiac,Solstice,PK3+,Information not available,No

In [237]:
# Create a dataframe only with Make: Cadillac
df_cadillac = df_chevrolet_renamed_column[df_chevrolet_renamed_column['Make'] == 'Cadillac']

In [238]:
# Check is the df is ok
df_cadillac.tail()

,Year,Make,Model,Security,Hardware Part Number,Is this hardware clonable?
634,2013,Cadillac,Escalade ESV,PK3+,Information not available,No
635,2013,Cadillac,ATS,PK3+\nSmart Key,E39A-H98S,Yes
636,2013,Cadillac,SRX,PK3+\nSmart Key,E39A-H98S,Yes
637,2013,Cadillac,XTS,PK3+\nSmart Key,E39A-H98S,Yes
638,2013,Cadillac,CTS,PK3+/KA,E39-X94S,Yes

In [239]:
# Create a dataframe only with Make: Buick
df_buick = df_chevrolet_renamed_column[df_chevrolet_renamed_column['Make'] == 'Buick']

In [240]:
# Check is the df is ok
df_buick.tail()

,Year,Make,Model,Security,Hardware Part Number,Is this hardware clonable?
628,2013,Buick,Enclave,PK3+,E39A-H98S,Yes
629,2013,Buick,Encore,PK3+\nSmart Key,E78-AB8,Yes
630,2013,Buick,LaCrosse,PK3+\nSmart Key,E39A-H98S,Yes
631,2013,Buick,Regal,PK3+\nSmart Key,E39A-H98S,Yes
632,2013,Buick,Verano,PK3+\nSmart Key,E39-X94S,Yes

In [241]:
# Create a dataframe only with Make: Oldsmobile
df_oldsmobile = df_chevrolet_renamed_column[df_chevrolet_renamed_column['Make'] == 'Oldsmobile']

In [242]:
# Check is the df is ok
df_oldsmobile.tail()

,Year,Make,Model,Security,Hardware Part Number,Is this hardware clonable?
237,2003,Oldsmobile,Alero,PL2,U44C-482,No
238,2003,Oldsmobile,Bravada,PL2,P10,No
272,2004,Oldsmobile,Silhouette,PK3,U44C-721,No
273,2004,Oldsmobile,Alero,PL2,U44C-721,No
274,2004,Oldsmobile,Bravada,PL2,P10,No

In [243]:
# Create a dataframe only with Make: GMC
df_gmc = df_chevrolet_renamed_column[df_chevrolet_renamed_column['Make'] == 'GMC']

In [244]:
# Check is the df is ok
df_gmc.tail()

,Year,Make,Model,Security,Hardware Part Number,Is this hardware clonable?
657,2013,GMC,Savana,PK3+,E38-AK8,Yes
658,2013,GMC,Sierra,PK3+,E86-A24,No
659,2013,GMC,Yukon XL,PK3+,Information not available,No
660,2013,GMC,Yukon Denali,PK3+,E38-AK8,Yes
661,2013,GMC,Terrain,PK3+\nSmart Key,E39A-H98S,Yes

In [245]:
# Create a dataframe only with Make: Saturn
df_saturn = df_chevrolet_renamed_column[df_chevrolet_renamed_column['Make'] == 'Saturn']

In [246]:
# Check is the df is ok
df_saturn.tail()

,Year,Make,Model,Security,Hardware Part Number,Is this hardware clonable?
519,2009,Saturn,Vue,PK3+,E67-TP1,No
558,2010,Saturn,Aura,PK3+,Information not available,No
559,2010,Saturn,Outlook,PK3+,Information not available,No
560,2010,Saturn,Sky,PK3+,Information not available,No
561,2010,Saturn,Vue,PK3+,Information not available,No

In [247]:
# Create a dataframe only with Make: Hummer
df_hummer = df_chevrolet_renamed_column[df_chevrolet_renamed_column['Make'] == 'Hummer']

In [248]:
# Check is the df is ok
df_hummer.tail()

,Year,Make,Model,Security,Hardware Part Number,Is this hardware clonable?
504,2009,Hummer,H2 SUT,PK3+,Information not available,No
505,2009,Hummer,H3,PL3/PK3+,Information not available,No
551,2010,Hummer,H2,PK3+,Information not available,No
552,2010,Hummer,H2 SUT,PK3+,Information not available,No
553,2010,Hummer,H3,PL3/PK3+,Information not available,No

In [249]:
# Create a dictionary with the dataframes from each make
dataframes_each_make = {
                        'Ford': df_ford_updated,
                        'Lincoln': df_lincoln_updated,
                        'Mercury': df_mercury_updated,
                        'Mazda': df_mazda_updated,
                        'Chevrolet': df_chevy_filtered,
                        'Pontiac': df_pontiac,
                        'Cadillac': df_cadillac,
                        'Buick': df_buick,
                        'Oldsmobile': df_oldsmobile,
                        'GMC': df_gmc,
                        'Saturn': df_saturn,
                        'Hummer': df_hummer
}

This is a test to confirm if the dictionary works as intended.

In [250]:
# These variables similate the ones the user customer will see on the application.
selected_year = 2005
selected_make = 'Cadillac'
selected_model = 'CTS'

In [251]:
# Get the dataframe from the dictionary based on the selected_make variable
selected_df = dataframes_each_make.get(selected_make)

In [252]:
# Filter the dataframe chosen based on the year and model selected. The dataframe will become one line where the values will be shown to the user.
df_selected_filtered = selected_df[(selected_df['Year'] == selected_year) & (selected_df['Model'] == selected_model)]

In [253]:
# Print
df_selected_filtered

,Year,Make,Model,Security,Hardware Part Number,Is this hardware clonable?
288,2005,Cadillac,CTS,PK3+,U44G-G45,No

In [254]:
# Acess the values of the 1st (and the only line) and store in a variable
row_df_selected_filtered = df_selected_filtered.iloc[0]

In [255]:
# Iterate in each column of the dataframe and print the values of each line
for column in df_selected_filtered.columns:
    print(f"{column}: {row_df_selected_filtered[column]}")

Year: 2005
Make: Cadillac
Model: CTS
Security: PK3+
Hardware Part Number: U44G-G45
Is this hardware clonable?: No

In [18]:
df_lincoln_updated.to_excel('C:\Language_Projects\Language_Projects\Python\Flagship_1\Immo_Assistant.app\dataframe_each_make_xlsx_file\df_lincoln_updated.xlsx')

<>:1: SyntaxWarning: invalid escape sequence '\L'
<>:1: SyntaxWarning: invalid escape sequence '\L'
C:\Users\Weverson Barbieri\AppData\Local\Temp\ipykernel_23156\1676507596.py:1: SyntaxWarning: invalid escape sequence '\L'
  df_lincoln_updated.to_excel('C:\Language_Projects\Language_Projects\Python\Flagship_1\Immo_Assistant.app\dataframe_each_make_xlsx_file\df_lincoln_updated.xlsx')

In [17]:
# Instead of copying all the code above, used to manipulate the main dataframe named df in this notebook, the dataframes created from the main one will be 
# saved in excel format and then loaded in immo_Assistant.py, followed by the code to create the application with the Streamlit library.
df_ford_new.to_excel('C:\Language_Projects\Language_Projects\Python\Flagship_1\Immo_Assistant.app\dataframe_each_make_xlsx_file\df_ford_new.xlsx')
df_lincoln_updated.to_excel('C:\Language_Projects\Language_Projects\Python\Flagship_1\Immo_Assistant.app\dataframe_each_make_xlsx_file\df_lincoln_updated.xlsx')
df_mercury_updated.to_excel('C:\Language_Projects\Language_Projects\Python\Flagship_1\Immo_Assistant.app\dataframe_each_make_xlsx_file\df_mercury_updated.xlsx')
df_mazda_updated.to_excel('C:\Language_Projects\Language_Projects\Python\Flagship_1\Immo_Assistant.app\dataframe_each_make_xlsx_file\df_mazda_updated.xlsx')
df_chevy_filtered.to_excel('C:\Language_Projects\Language_Projects\Python\Flagship_1\Immo_Assistant.app\dataframe_each_make_xlsx_file\df_chevy_filtered.xlsx')
df_pontiac.to_excel('C:\Language_Projects\Language_Projects\Python\Flagship_1\Immo_Assistant.app\dataframe_each_make_xlsx_file\df_pontiac.xlsx')
df_cadillac.to_excel('C:\Language_Projects\Language_Projects\Python\Flagship_1\Immo_Assistant.app\dataframe_each_make_xlsx_file\df_cadillac.xlsx')
df_buick.to_excel('C:\Language_Projects\Language_Projects\Python\Flagship_1\Immo_Assistant.app\dataframe_each_make_xlsx_file\df_buick.xlsx')
df_oldsmobile.to_excel('C:\Language_Projects\Language_Projects\Python\Flagship_1\Immo_Assistant.app\dataframe_each_make_xlsx_file\df_oldsmobile.xlsx')
df_gmc.to_excel('C:\Language_Projects\Language_Projects\Python\Flagship_1\Immo_Assistant.app\dataframe_each_make_xlsx_file\df_gmc.xlsx')
df_saturn.to_excel('C:\Language_Projects\Language_Projects\Python\Flagship_1\Immo_Assistant.app\dataframe_each_make_xlsx_file\df_saturn.xlsx')
df_hummer.to_excel('C:\Language_Projects\Language_Projects\Python\Flagship_1\Immo_Assistant.app\dataframe_each_make_xlsx_file\df_hummer.xlsx')

<>:3: SyntaxWarning: invalid escape sequence '\L'
<>:4: SyntaxWarning: invalid escape sequence '\L'
<>:5: SyntaxWarning: invalid escape sequence '\L'
<>:6: SyntaxWarning: invalid escape sequence '\L'
<>:7: SyntaxWarning: invalid escape sequence '\L'
<>:8: SyntaxWarning: invalid escape sequence '\L'
<>:9: SyntaxWarning: invalid escape sequence '\L'
<>:10: SyntaxWarning: invalid escape sequence '\L'
<>:11: SyntaxWarning: invalid escape sequence '\L'
<>:12: SyntaxWarning: invalid escape sequence '\L'
<>:13: SyntaxWarning: invalid escape sequence '\L'
<>:14: SyntaxWarning: invalid escape sequence '\L'
<>:3: SyntaxWarning: invalid escape sequence '\L'
<>:4: SyntaxWarning: invalid escape sequence '\L'
<>:5: SyntaxWarning: invalid escape sequence '\L'
<>:6: SyntaxWarning: invalid escape sequence '\L'
<>:7: SyntaxWarning: invalid escape sequence '\L'
<>:8: SyntaxWarning: invalid escape sequence '\L'
<>:9: SyntaxWarning: invalid escape sequence '\L'
<>:10: SyntaxWarning: invalid escape sequence '\L'
<>:11: SyntaxWarning: invalid escape sequence '\L'
<>:12: SyntaxWarning: invalid escape sequence '\L'
<>:13: SyntaxWarning: invalid escape sequence '\L'
<>:14: SyntaxWarning: invalid escape sequence '\L'
C:\Users\Weverson Barbieri\AppData\Local\Temp\ipykernel_23156\3684713339.py:3: SyntaxWarning: invalid escape sequence '\L'
  df_ford_new.to_excel('C:\Language_Projects\Language_Projects\Python\Flagship_1\Immo_Assistant.app\dataframe_each_make_xlsx_file\df_ford_new.xlsx')
C:\Users\Weverson Barbieri\AppData\Local\Temp\ipykernel_23156\3684713339.py:4: SyntaxWarning: invalid escape sequence '\L'
  df_lincoln_updated.to_excel('C:\Language_Projects\Language_Projects\Python\Flagship_1\Immo_Assistant.app\dataframe_each_make_xlsx_file\df_lincoln_updated.xlsx')
C:\Users\Weverson Barbieri\AppData\Local\Temp\ipykernel_23156\3684713339.py:5: SyntaxWarning: invalid escape sequence '\L'
  df_mercury_updated.to_excel('C:\Language_Projects\Language_Projects\Python\Flagship_1\Immo_Assistant.app\dataframe_each_make_xlsx_file\df_mercury_updated.xlsx')
C:\Users\Weverson Barbieri\AppData\Local\Temp\ipykernel_23156\3684713339.py:6: SyntaxWarning: invalid escape sequence '\L'
  df_mazda_updated.to_excel('C:\Language_Projects\Language_Projects\Python\Flagship_1\Immo_Assistant.app\dataframe_each_make_xlsx_file\df_mazda_updated.xlsx')
C:\Users\Weverson Barbieri\AppData\Local\Temp\ipykernel_23156\3684713339.py:7: SyntaxWarning: invalid escape sequence '\L'
  df_chevy_filtered.to_excel('C:\Language_Projects\Language_Projects\Python\Flagship_1\Immo_Assistant.app\dataframe_each_make_xlsx_file\df_chevy_filtered.xlsx')
C:\Users\Weverson Barbieri\AppData\Local\Temp\ipykernel_23156\3684713339.py:8: SyntaxWarning: invalid escape sequence '\L'
  df_pontiac.to_excel('C:\Language_Projects\Language_Projects\Python\Flagship_1\Immo_Assistant.app\dataframe_each_make_xlsx_file\df_pontiac.xlsx')
C:\Users\Weverson Barbieri\AppData\Local\Temp\ipykernel_23156\3684713339.py:9: SyntaxWarning: invalid escape sequence '\L'
  df_cadillac.to_excel('C:\Language_Projects\Language_Projects\Python\Flagship_1\Immo_Assistant.app\dataframe_each_make_xlsx_file\df_cadillac.xlsx')
C:\Users\Weverson Barbieri\AppData\Local\Temp\ipykernel_23156\3684713339.py:10: SyntaxWarning: invalid escape sequence '\L'
  df_buick.to_excel('C:\Language_Projects\Language_Projects\Python\Flagship_1\Immo_Assistant.app\dataframe_each_make_xlsx_file\df_buick.xlsx')
C:\Users\Weverson Barbieri\AppData\Local\Temp\ipykernel_23156\3684713339.py:11: SyntaxWarning: invalid escape sequence '\L'
  df_oldsmobile.to_excel('C:\Language_Projects\Language_Projects\Python\Flagship_1\Immo_Assistant.app\dataframe_each_make_xlsx_file\df_oldsmobile.xlsx')
C:\Users\Weverson Barbieri\AppData\Local\Temp\ipykernel_23156\3684713339.py:12: SyntaxWarning: invalid escape sequence '\L'
  df_gmc.to_excel('C:\Language_Projects\Language_Projects\Python\Flagship_1\Immo_Assistant.app\dataframe_each_make_xlsx_file\df_gmc.xlsx')
C:\Users\Weverson Barbieri\AppData\Local\Temp\ipykernel_23156\3684713339.py:13: SyntaxWarning: invalid escape sequence '\L'
  df_saturn.to_excel('C:\Language_Projects\Language_Projects\Python\Flagship_1\Immo_Assistant.app\dataframe_each_make_xlsx_file\df_saturn.xlsx')
C:\Users\Weverson Barbieri\AppData\Local\Temp\ipykernel_23156\3684713339.py:14: SyntaxWarning: invalid escape sequence '\L'
  df_hummer.to_excel('C:\Language_Projects\Language_Projects\Python\Flagship_1\Immo_Assistant.app\dataframe_each_make_xlsx_file\df_hummer.xlsx')
C:\Users\Weverson Barbieri\AppData\Local\Temp\ipykernel_23156\3684713339.py:3: SyntaxWarning: invalid escape sequence '\L'
  df_ford_new.to_excel('C:\Language_Projects\Language_Projects\Python\Flagship_1\Immo_Assistant.app\dataframe_each_make_xlsx_file\df_ford_new.xlsx')
C:\Users\Weverson Barbieri\AppData\Local\Temp\ipykernel_23156\3684713339.py:4: SyntaxWarning: invalid escape sequence '\L'
  df_lincoln_updated.to_excel('C:\Language_Projects\Language_Projects\Python\Flagship_1\Immo_Assistant.app\dataframe_each_make_xlsx_file\df_lincoln_updated.xlsx')
C:\Users\Weverson Barbieri\AppData\Local\Temp\ipykernel_23156\3684713339.py:5: SyntaxWarning: invalid escape sequence '\L'
  df_mercury_updated.to_excel('C:\Language_Projects\Language_Projects\Python\Flagship_1\Immo_Assistant.app\dataframe_each_make_xlsx_file\df_mercury_updated.xlsx')
C:\Users\Weverson Barbieri\AppData\Local\Temp\ipykernel_23156\3684713339.py:6: SyntaxWarning: invalid escape sequence '\L'
  df_mazda_updated.to_excel('C:\Language_Projects\Language_Projects\Python\Flagship_1\Immo_Assistant.app\dataframe_each_make_xlsx_file\df_mazda_updated.xlsx')
C:\Users\Weverson Barbieri\AppData\Local\Temp\ipykernel_23156\3684713339.py:7: SyntaxWarning: invalid escape sequence '\L'
  df_chevy_filtered.to_excel('C:\Language_Projects\Language_Projects\Python\Flagship_1\Immo_Assistant.app\dataframe_each_make_xlsx_file\df_chevy_filtered.xlsx')
C:\Users\Weverson Barbieri\AppData\Local\Temp\ipykernel_23156\3684713339.py:8: SyntaxWarning: invalid escape sequence '\L'
  df_pontiac.to_excel('C:\Language_Projects\Language_Projects\Python\Flagship_1\Immo_Assistant.app\dataframe_each_make_xlsx_file\df_pontiac.xlsx')
C:\Users\Weverson Barbieri\AppData\Local\Temp\ipykernel_23156\3684713339.py:9: SyntaxWarning: invalid escape sequence '\L'
  df_cadillac.to_excel('C:\Language_Projects\Language_Projects\Python\Flagship_1\Immo_Assistant.app\dataframe_each_make_xlsx_file\df_cadillac.xlsx')
C:\Users\Weverson Barbieri\AppData\Local\Temp\ipykernel_23156\3684713339.py:10: SyntaxWarning: invalid escape sequence '\L'
  df_buick.to_excel('C:\Language_Projects\Language_Projects\Python\Flagship_1\Immo_Assistant.app\dataframe_each_make_xlsx_file\df_buick.xlsx')
C:\Users\Weverson Barbieri\AppData\Local\Temp\ipykernel_23156\3684713339.py:11: SyntaxWarning: invalid escape sequence '\L'
  df_oldsmobile.to_excel('C:\Language_Projects\Language_Projects\Python\Flagship_1\Immo_Assistant.app\dataframe_each_make_xlsx_file\df_oldsmobile.xlsx')
C:\Users\Weverson Barbieri\AppData\Local\Temp\ipykernel_23156\3684713339.py:12: SyntaxWarning: invalid escape sequence '\L'
  df_gmc.to_excel('C:\Language_Projects\Language_Projects\Python\Flagship_1\Immo_Assistant.app\dataframe_each_make_xlsx_file\df_gmc.xlsx')
C:\Users\Weverson Barbieri\AppData\Local\Temp\ipykernel_23156\3684713339.py:13: SyntaxWarning: invalid escape sequence '\L'
  df_saturn.to_excel('C:\Language_Projects\Language_Projects\Python\Flagship_1\Immo_Assistant.app\dataframe_each_make_xlsx_file\df_saturn.xlsx')
C:\Users\Weverson Barbieri\AppData\Local\Temp\ipykernel_23156\3684713339.py:14: SyntaxWarning: invalid escape sequence '\L'
  df_hummer.to_excel('C:\Language_Projects\Language_Projects\Python\Flagship_1\Immo_Assistant.app\dataframe_each_make_xlsx_file\df_hummer.xlsx')

NameError: name 'df_ford_new' is not defined

In [258]:
# Create an array with all makes of the main df
make_list = df['Make'].unique()

In [259]:
# Create a list of all makes the dataframe is ready
list_df_make_ready = []

# Loop in the dictionary to get the make names
for make in dataframes_each_make:
    # Store the makes of the dictironary into a list
    list_df_make_ready.append(make)

In [260]:
# Create a check_list with makes the df is not ready yet using list comprehensions
make_to_be_done = [make for make in make_list if make not in list_df_make_ready]

In [261]:
# Print the check list
print(make_to_be_done)

['Acura', 'Honda', 'BMW', 'Lexus', 'Toyota', 'Chrysler', 'Dodge', 'Infiniti', 'Jaguar', 'Nissan', 'Plymouth', 'Jeep', 'Audi', 'Mitsubishi', 'Volkswagen', 'Land Rover', 'Mini', 'Rolls-Royce', 'Scion', 'Subaru', 'Fiat']

In [262]:
# Print make check list to see what is the next make to create the df
print(make_to_be_done)

['Acura', 'Honda', 'BMW', 'Lexus', 'Toyota', 'Chrysler', 'Dodge', 'Infiniti', 'Jaguar', 'Nissan', 'Plymouth', 'Jeep', 'Audi', 'Mitsubishi', 'Volkswagen', 'Land Rover', 'Mini', 'Rolls-Royce', 'Scion', 'Subaru', 'Fiat']

In [263]:
# Create a function to create the dataframe for each make
def create_make_df(make):
    return df[df['Make'] == make]

In [264]:
# Function to create a list w/ unique values from the columns 
def strings_from_column(df_make, column):
    # List to store the strings from the columns
    strings_from_column_list = []
    # Loop to get the strings from each row based on the column given
    for string in df_make[column]:
        # Store the strings in the list
        strings_from_column_list.append(string)
    # Return a list w/ unique values/strings from the column given
    return set(strings_from_column_list)

In [265]:
# Count the makes to confirm if all dataframes were created
make_count = strings_from_column(df, 'Make')

In [266]:
# Count the makes
pd.DataFrame(make_list).count()

0    33
dtype: int64